import './global.css';
import { Locator } from '../components/locator';
import { AppQueryClientProvider } from '../lib/providers/query-client-provider';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppQueryClientProvider>
          {children}
          <Locator />
        </AppQueryClientProvider>
      </body>
    </html>
  );
}
