import './global.css';
import { Locator } from '../components/locator';
import { AppQueryClientProvider } from '../lib/providers/query-client-provider';
import { Header } from '../components/layout/header';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col h-[100dvh] overflow-hidden bg-neutral-950 text-warm-50">
        <AppQueryClientProvider>
          <Header />
          <main className="flex-1 flex flex-col min-h-0 relative">
            {children}
          </main>
          <Locator />
        </AppQueryClientProvider>
      </body>
    </html>
  );
}
